create table dailyexpense (
	id INT,
	expense DECIMAL(4,1),
	expensedate DATE,
	expensenote TEXT,
	expensecategory VARCHAR(50),
	userid INT
);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (1, 165.2, '11/24/2021', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Fuscia', 1);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (2, 175.7, '1/12/2022', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Puce', 2);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (3, 65.7, '10/17/2021', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Green', 3);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (4, 65.3, '6/19/2021', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Crimson', 4);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (5, 191.6, '5/30/2022', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Purple', 5);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (6, 67.9, '1/28/2022', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Puce', 6);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (7, 140.2, '1/31/2022', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Pink', 7);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (8, 36.3, '4/8/2022', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Mauv', 8);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (9, 51.4, '3/7/2022', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Crimson', 9);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (10, 47.9, '8/24/2021', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Green', 10);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (11, 134.3, '10/27/2021', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Blue', 11);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (12, 34.2, '6/5/2022', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Puce', 12);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (13, 25.9, '4/20/2022', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Turquoise', 13);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (14, 172.4, '11/22/2021', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Indigo', 14);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (15, 131.8, '7/12/2021', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Turquoise', 15);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (16, 4.0, '3/31/2022', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Aquamarine', 16);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (17, 106.3, '8/11/2021', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Khaki', 17);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (18, 79.4, '6/15/2021', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Blue', 18);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (19, 194.7, '8/23/2021', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Blue', 19);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (20, 92.5, '1/3/2022', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Maroon', 20);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (21, 22.2, '5/26/2022', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Yellow', 21);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (22, 167.2, '10/27/2021', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Turquoise', 22);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (23, 117.7, '8/28/2021', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Yellow', 23);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (24, 89.8, '10/4/2021', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Teal', 24);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (25, 118.5, '12/31/2021', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Puce', 25);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (26, 121.9, '1/15/2022', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Blue', 26);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (27, 177.0, '12/14/2021', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Mauv', 27);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (28, 70.0, '12/1/2021', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Crimson', 28);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (29, 143.8, '4/4/2022', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Yellow', 29);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (30, 153.2, '11/1/2021', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Yellow', 30);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (31, 60.4, '3/31/2022', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Aquamarine', 31);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (32, 104.3, '2/17/2022', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Crimson', 32);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (33, 9.6, '8/1/2021', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Blue', 33);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (34, 96.6, '6/6/2022', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Blue', 34);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (35, 115.6, '3/15/2022', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Green', 35);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (36, 161.5, '4/2/2022', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Indigo', 36);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (37, 179.6, '7/12/2021', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Crimson', 37);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (38, 165.2, '6/3/2022', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Crimson', 38);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (39, 187.4, '3/30/2022', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Maroon', 39);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (40, 46.3, '3/30/2022', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Green', 40);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (41, 42.4, '9/17/2021', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Maroon', 41);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (42, 31.8, '1/13/2022', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Puce', 42);
insert into dailyexpense (id, expense, expensedate, expensenote, expensecategory, userid) values (43, 17.1, '8/7/2021', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Aquamarine', 43);
